package com.vexelcore.prison.upgrades;

public enum UpgradeType {
    EFFICIENCY, FORTUNE, EXPLOSIVE, LASER, VEIN_MINER, TOKEN_FINDER, KEY_FINDER,
    AUTOSELL_BOOST, AUTOREPAIR, XP_MAGNET, LUCKY_CHARM, BLACKHOLE, GEM_FINDER,
    HASTE_SURGE, COMBO_STREAK
}
